{% set name = "bargeparse" %}
{% set version = "0.9.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bargeparse-{{ version }}.tar.gz
  sha256: 3d61663f6ad3f09272a5b13015c8720cecca1b19d39f0b22c97b75bfdb8c5172

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - bargeparse
  imports:
    - bargeparse
  commands:
    - pytest
  requires:
    - pytest

about:
  home: https://github.com/shangxiao/bargeparse
  summary: Instrospect function signatures to construct a CLI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shangxiao
