{% set name = "bargeparse" %}
{% set version = "0.9.1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bargeparse-{{ version }}.tar.gz
  sha256: bf9bd349ef4980a95bf1711dc18a16e63510a30d3dd73061c72baeb3336d449b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - bargeparse
  imports:
    - bargeparse
  commands:
    - pytest
  requires:
    - pytest

about:
  home: https://github.com/shangxiao/bargeparse
  summary: Instrospect function signatures to construct a CLI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shangxiao
